# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

before_all do
   ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
  end

    desc "Runs all the tests"
    lane :run_test do
      gradle(
        task: "test",
        build_type: "Debug"
      )
    end

  desc "Submit a New Debug Build to Firebase App Distribution"
   lane :debug_build_submit do
     gradle(
       task: "clean assemble",
       build_type: "Debug"
     )
     @apk_output_info = load_json(json_path: "./app/build/outputs/apk/debug/output.json")
     commit = last_git_commit
     author = commit[:author] # author of the commit
     author_email = commit[:author_email] # email of the author of the commit
     short_hash = commit[:abbreviated_commit_hash] # short sha of commit
     message = commit[:message]

     firebase_app_distribution(
             app: ENV["FIREBASE_APP_ID"],
           # groups: "android-testers",
             firebase_cli_token: ENV["FIREBASE_TOKEN"],
             release_notes: "Build for Commit: #{message} with hash #{short_hash} by #{author} => #{author_email} ",
             debug: true
     )

     slack(
             # message to display
             message: "Android Debug Build Successfully Released & Ready for Testing!",
             payload: {
                 "Build_Date" => Time.new.to_s,
                 "Build_Generated_By" => "#{author}",
                 "Distributed_Version": "" + @apk_output_info[0]['apkData']['versionName']
             },
             default_payloads: [:git_branch, :git_author],
             success: true
     )
   end

   after_all do |lane|
   error do
       slack(
         message: exception.message,
         success: false
         )
     end
 end

 # Not yet implemented

   desc "Deploy a new version to the Google Play"
   lane :store_deploy do
     gradle(task: "clean assembleRelease")
     upload_to_play_store
   end

   end